/**
 * Regenerates the catalogue seed: `data/competitions.csv`, `data/grade_weights.csv`
 * and the `drizzle/0001_seed.sql` migration that loads them.
 *
 * Run after editing src/pipeline/seed/catalogue.ts:
 *   pnpm exec tsx scripts/generate-seed.ts
 *
 * The CSVs are the readable artefact; the SQL is derived so local and remote D1 seed
 * identically through `wrangler d1 migrations apply`.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { toCsv } from '../src/pipeline/csv.ts';
import {
    COMPETITION_SEEDS,
    buildGradeWeights,
} from '../src/pipeline/seed/catalogue.ts';

const root = resolve(import.meta.dirname, '..');

function sqlText(value: string | null): string {
    return value === null ? 'NULL' : `'${value.replaceAll("'", "''")}'`;
}

const competitionRows = COMPETITION_SEEDS.map((competition) => ({
    has_data: competition.hasData ? 1 : 0,
    key: competition.key,
    name: competition.name,
    playhq_org_id: competition.playhqOrgId,
}));

const gradeWeights = buildGradeWeights();

const weightRows = gradeWeights.map((weight) => ({
    competition_key: weight.competitionKey,
    division: weight.division,
    label: weight.label,
    tier: weight.tier,
    weight: weight.weight,
}));

writeFileSync(resolve(root, 'data/competitions.csv'), toCsv(competitionRows));
writeFileSync(resolve(root, 'data/grade_weights.csv'), toCsv(weightRows));

const statements = [
    '-- Generated by scripts/generate-seed.ts. Do not edit by hand.',
    '-- Catalogue seed: competitions and championship grade weights.',
    '',
    ...COMPETITION_SEEDS.map(
        (competition) =>
            `INSERT INTO competitions (key, name, playhq_org_id) VALUES (${sqlText(competition.key)}, ${sqlText(competition.name)}, ${sqlText(competition.playhqOrgId)}) ON CONFLICT(key) DO UPDATE SET name = excluded.name, playhq_org_id = excluded.playhq_org_id;`,
    ),
    '',
    ...gradeWeights.map(
        (weight) =>
            `INSERT INTO grade_weights (competition_id, tier, division, label, weight) SELECT id, ${weight.tier}, ${weight.division ?? 'NULL'}, ${sqlText(weight.label)}, ${weight.weight} FROM competitions WHERE key = ${sqlText(weight.competitionKey)};`,
    ),
    '',
];

writeFileSync(resolve(root, 'drizzle/0001_seed.sql'), statements.join('\n'));

console.warn(
    `seeded ${competitionRows.length} competitions, ${weightRows.length} grade weights`,
);
